deDts:
  datasource:
    db-url: jdbc:mysql://localhost:3306/banco
    username: root
    password: senha criptografada
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  mail:  
    username: email 
    password: senha criptografada    
    port: 587
    host: smtp.gmail.com    
    properties:
     mail.smtp.auth: true
     mail.smtp.starttls.enable: true
     mail.smtp.starttls.required: true
     mail.transport.protocol: smtp
      
  jpa:   
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      javax.persistence.validation.mode: none

    
 

 